

[34m[1mwandb[39m[22m: Downloading large artifact model-mheh9e55:latest, 1673.44MB. 7 files... Done. 0:0:0

[34m[1mwandb[39m[22m: Downloading large artifact model-mheh9e55:latest, 1673.44MB. 7 files... Done. 0:0:0
  0%|          | 0/1 [00:00<?, ?it/s]
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 152, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 405, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 170, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 114, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 395, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-04-21 14:44:10.612550: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:61]
********************************
Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
Compiling module pmap_p_generate.207
********************************
Traceback (most recent call last):
  File "/Users/max/Developer/future-studio-lab/dalle-playground/backend/app.py", line 151, in <module>
    generate_images("warm-up", 1)
  File "/Users/max/Developer/future-studio-lab/dalle-playground/backend/app.py", line 111, in generate_images
    encoded_images = p_generate(tokenized_prompt, shard_prng_key(subkey),
  File "/usr/local/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jax/_src/api.py", line 2013, in cache_miss
    out_tree, out_flat = f_pmapped_(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jax/_src/api.py", line 1889, in pmap_f
    out = pxla.xla_pmap(
  File "/usr/local/lib/python3.9/site-packages/jax/core.py", line 1863, in bind
    return map_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.9/site-packages/jax/core.py", line 1895, in map_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/usr/local/lib/python3.9/site-packages/jax/core.py", line 1866, in process
    return trace.process_map(self, fun, tracers, params)
  File "/usr/local/lib/python3.9/site-packages/jax/core.py", line 660, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 801, in xla_pmap_impl
    compiled_fun, fingerprint = parallel_callable(
  File "/usr/local/lib/python3.9/site-packages/jax/linear_util.py", line 285, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 832, in parallel_callable
    pmap_executable = pmap_computation.compile()
  File "/usr/local/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 1097, in compile
    self._executable = PmapExecutable.from_hlo(self._hlo, **self.compile_args)
  File "/usr/local/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 1222, in from_hlo
    compiled = dispatch.compile_or_get_cached(
  File "/usr/local/lib/python3.9/site-packages/jax/_src/dispatch.py", line 696, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options)
  File "/usr/local/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jax/_src/dispatch.py", line 650, in backend_compile
    return backend.compile(built_c, compile_options=options)
KeyboardInterrupt